packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@biomejs/biome': ^2.3.2
  'typescript': 5.9.3
  'vitest': ^3.2.0
  '@cloudflare/vitest-pool-workers': ^0.9.3
  '@playwright/test': ^1.56.0
  '@playwright/experimental-ct-react': ^1.56.0
  '@axe-core/playwright': ^4.10.0
  '@vitest/coverage-v8': ^3.2.0
  '@vitest/ui': ^3.2.0
  '@testing-library/react': ^16.1.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.5.2
  'happy-dom': ^20.0.10
  'vitest-axe': ^0.1.0
  'zod': ^4.0.0
  'zocker': ^3.0.0
  'msw': ^2.11.6
  'hono': ^4.10.4
  'lit': ^3.3.1
  'react': ^19.2.0
  'react-dom': ^19.2.0
  '@changesets/cli': ^2.29.5
  'lefthook': ^1.10.0
  '@types/node': ^24.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@vitejs/plugin-react': ^4.3.4
