packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^20.19.0
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  typescript: ^5.5.2
  vite: ^5.3.1
  vitest: ^3.2.3
  '@vitejs/plugin-react': ^4.5.1
  '@tailwindcss/vite': ^4.1.8
  tailwindcss: ^4.1.8
  '@testing-library/react': ^16.3.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.6.1
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-tabs': ^1.1.12
  clsx: ^2.1.1
  tailwind-merge: ^3.3.0
  zod: ^3.23.8
  framer-motion: ^11.13.5
  react-colorful: ^5.6.1
  gsap: ^3.12.2

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
