packages:
  - apps/*
  - packages/*

# Shared dependency catalog for version consistency
catalog:
  # Core TypeScript toolchain
  typescript: 5.9.2
  '@types/node': 24.4.0

  # Build tools optimized for Workers
  vite: ^7.0.6
  '@vitejs/plugin-react': ^4.7.0
  esbuild: ^0.24.2

  # Testing infrastructure
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/browser': ^3.2.4
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@playwright/test': ^1.55.0
  '@playwright/experimental-ct-react': ^1.55.0
  '@cloudflare/vitest-pool-workers': ^0.9.1
  jsdom: ^26.1.0

  # React 19 ecosystem
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7

  # Styling with Tailwind CSS v4
  tailwindcss: 4.1.12
  '@tailwindcss/vite': ^4.1.11

  # Core utilities
  clsx: 2.1.1
  tailwind-merge: 3.3.1
  zod: 4.0.16
  fs-extra: ^11.2.0
  '@types/fs-extra': ^11.0.4
  sqids: ^0.3.0

  # Code quality
  '@biomejs/biome': ^2.2.2

  # Cloudflare Workers toolchain
  wrangler: ^4.34.0
  '@hono/zod-validator': ^0.7.2
  hono: ^4.9.6

  # Anthropic SDK for AI features
  '@anthropic-ai/sdk': ^0.60.0

  # Next.js for websites
  next: ^15.2.6
  '@next/mdx': ^15.2.6
  '@mdx-js/react': ^3.2.0
  '@mdx-js/loader': ^3.2.0

  # Color utilities
  colorjs.io: ^0.5.2
  apca-w3: ^0.1.9
  chroma-js: ^2.6.0
  '@types/chroma-js': ^2.4.4

# Native dependencies that must be built
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - workerd
  - '@cloudflare/workerd-darwin-64'
  - '@cloudflare/workerd-linux-64'
