packages:
  - apps/*
  - packages/*

catalog:
  '@anthropic-ai/sdk': ^0.60.0
  '@biomejs/biome': ^2.2.2
  '@cloudflare/vitest-pool-workers': ^0.9.1
  '@hono/zod-validator': ^0.7.2
  '@mdx-js/loader': ^3.2.0
  '@mdx-js/react': ^3.2.0
  '@next/mdx': ^15.2.6
  '@playwright/experimental-ct-react': ^1.55.0
  '@playwright/test': ^1.55.0
  '@tailwindcss/vite': ^4.1.11
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/chroma-js': ^2.4.4
  '@types/fs-extra': ^11.0.4
  '@types/node': 24.4.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^4.7.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  apca-w3: ^0.1.9
  chroma-js: ^2.6.0
  clsx: 2.1.1
  colorjs.io: ^0.5.2
  esbuild: ^0.24.2
  fs-extra: ^11.2.0
  hono: ^4.9.6
  jsdom: ^26.1.0
  next: ^15.2.6
  react: ^19.1.1
  react-dom: ^19.1.1
  sqids: ^0.3.0
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.12
  typescript: 5.9.2
  vite: ^7.0.6
  vitest: ^3.2.4
  wrangler: ^4.34.0
  zod: 4.0.16

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - workerd
  - '@cloudflare/workerd-darwin-64'
  - '@cloudflare/workerd-linux-64'
