packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.7.3
  vite: ^7.0.6
  '@vitejs/plugin-react': ^4.7.0
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/browser': ^3.2.4
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  tailwindcss: ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  zod: 4.0.16
  fs-extra: ^11.2.0
  '@types/fs-extra': ^11.0.4
  sqids: 0.3.0
  '@types/node': ^20.19.1
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  jsdom: ^26.1.0
  '@biomejs/biome': ^2.2.2

onlyBuiltDependencies:
  - esbuild
  - workerd
