/**
 * Integration tests for shared package types and schemas
 * Tests interaction with other packages and real-world usage scenarios
 */

import { describe, expect, it } from 'vitest';
import type { ColorValue, OKLCH, Token } from '../src/types.js';
import {
  ColorIntelligenceResponseSchema,
  ColorValueSchema,
  DesignSystemSchema,
  OKLCHSchema,
  TokenSchema,
} from '../src/types.js';

describe('Cross-package type compatibility', () => {
  it('should validate OKLCH objects used across packages', () => {
    // Test OKLCH format that would be used by color-utils and design-tokens
    const oklchColor: OKLCH = {
      l: 0.62,
      c: 0.18,
      h: 237,
      alpha: 0.95,
    };

    const result = OKLCHSchema.safeParse(oklchColor);
    expect(result.success).toBe(true);

    if (result.success) {
      expect(result.data.l).toBe(0.62);
      expect(result.data.c).toBe(0.18);
      expect(result.data.h).toBe(237);
      expect(result.data.alpha).toBe(0.95);
    }
  });

  it('should validate ColorValue objects with complex structures', () => {
    // Test ColorValue that would be generated by color-utils and consumed by design-tokens
    const complexColorValue: ColorValue = {
      name: 'corporate-blue',
      scale: [
        { l: 0.95, c: 0.02, h: 237 }, // 50
        { l: 0.87, c: 0.05, h: 237 }, // 100
        { l: 0.78, c: 0.08, h: 237 }, // 200
        { l: 0.68, c: 0.12, h: 237 }, // 300
        { l: 0.58, c: 0.15, h: 237 }, // 400
        { l: 0.48, c: 0.18, h: 237 }, // 500
        { l: 0.38, c: 0.16, h: 237 }, // 600
        { l: 0.28, c: 0.14, h: 237 }, // 700
        { l: 0.18, c: 0.12, h: 237 }, // 800
        { l: 0.08, c: 0.08, h: 237 }, // 900
      ],
      token: 'primary',
      value: '500',
      use: 'Primary brand color for CTAs and key UI elements',
      states: {
        hover: 'corporate-blue-600',
        focus: 'corporate-blue-700',
        active: 'corporate-blue-800',
        disabled: 'corporate-blue-300',
      },
      intelligence: {
        suggestedName: 'Corporate Blue',
        reasoning: 'Professional blue that conveys trust and reliability',
        emotionalImpact: 'Calm, trustworthy, and professional',
        culturalContext: 'Universally positive in business contexts',
        accessibilityNotes: 'Provides excellent contrast on white and light backgrounds',
        usageGuidance: 'Use for primary actions, links, and key brand elements',
      },
      harmonies: {
        complementary: { l: 0.58, c: 0.15, h: 57 },
        triadic: [
          { l: 0.58, c: 0.15, h: 357 },
          { l: 0.58, c: 0.15, h: 117 },
        ],
        analogous: [
          { l: 0.58, c: 0.15, h: 207 },
          { l: 0.58, c: 0.15, h: 267 },
        ],
        tetradic: [
          { l: 0.58, c: 0.15, h: 147 },
          { l: 0.58, c: 0.15, h: 57 },
          { l: 0.58, c: 0.15, h: 327 },
        ],
        monochromatic: [
          { l: 0.78, c: 0.08, h: 237 },
          { l: 0.68, c: 0.12, h: 237 },
          { l: 0.38, c: 0.16, h: 237 },
        ],
      },
      accessibility: {
        onWhite: {
          wcagAA: true,
          wcagAAA: true,
          contrastRatio: 8.2,
          aa: [5, 6, 7, 8, 9],
          aaa: [6, 7, 8, 9],
        },
        onBlack: {
          wcagAA: false,
          wcagAAA: false,
          contrastRatio: 2.1,
          aa: [0, 1, 2],
          aaa: [0, 1],
        },
      },
      analysis: {
        temperature: 'cool',
        isLight: false,
        name: 'corporate-blue',
      },
      tokenId: 'color-0.48-0.18-237',
    };

    const result = ColorValueSchema.safeParse(complexColorValue);
    expect(result.success).toBe(true);
  });

  it('should validate Token objects with AI intelligence metadata', () => {
    // Test Token that would be used by design-tokens with full AI metadata
    const aiToken: Token = {
      name: 'primary-action',
      value: 'oklch(0.48 0.18 237)',
      category: 'color',
      namespace: 'semantic',
      semanticMeaning: 'Primary action color for main user goals',
      usageContext: ['buttons', 'links', 'CTAs', 'active-states'],
      trustLevel: 'high',
      cognitiveLoad: 2,
      accessibilityLevel: 'AAA',
      consequence: 'reversible',
      applicableComponents: ['button', 'link', 'badge'],
      requiredForComponents: ['primary-button'],
      interactionType: 'active',
      animationSafe: true,
      generateUtilityClass: true,
      tailwindOverride: true,
      contrastRatio: 8.2,
      description: 'High-contrast primary color for maximum accessibility',
      pairedWith: ['primary-action-foreground', 'primary-action-border'],
      requiresConfirmation: false,
      generatedAt: '2024-01-15T10:30:00Z',
    };

    const result = TokenSchema.safeParse(aiToken);
    expect(result.success).toBe(true);

    if (result.success) {
      expect(result.data.trustLevel).toBe('high');
      expect(result.data.cognitiveLoad).toBe(2);
      expect(result.data.accessibilityLevel).toBe('AAA');
      expect(result.data.applicableComponents).toContain('button');
    }
  });

  it('should validate complete design system structure', () => {
    // Test DesignSystem that would be used across the entire monorepo
    const designSystem = {
      id: 'corporate-design-system',
      name: 'Corporate Design System v2.1',
      primaryColor: { l: 0.48, c: 0.18, h: 237 },
      tokens: [
        {
          name: 'primary',
          value: 'oklch(0.48 0.18 237)',
          category: 'color',
          namespace: 'semantic',
          trustLevel: 'high' as const,
          cognitiveLoad: 2,
        },
        {
          name: 'base-spacing',
          value: '1rem',
          category: 'spacing',
          namespace: 'size',
          mathRelationship: 'base * 1',
        },
      ],
      typography: {
        heading: 'Inter, system-ui, sans-serif',
        body: 'Inter, system-ui, sans-serif',
        mono: 'JetBrains Mono, Monaco, monospace',
        scale: {
          xs: 0.75,
          sm: 0.875,
          base: 1,
          lg: 1.125,
          xl: 1.25,
        },
      },
      intelligence: {
        colorVisionTested: ['normal', 'deuteranopia', 'protanopia'],
        contrastLevel: 'AAA' as const,
        components: {
          'primary-button': {
            cognitiveLoad: 2,
            attentionHierarchy: 'Primary action - maximum one per section',
            accessibilityRules: 'WCAG AAA, 44px minimum touch target, focus indicators',
            usageContext: 'Main user goals and primary CTAs',
            safetyConstraints: 'Destructive actions require confirmation dialog',
          },
        },
      },
      metadata: {
        created: '2024-01-15T08:00:00Z',
        updated: '2024-01-15T10:30:00Z',
        version: '2.1.0',
      },
    };

    const result = DesignSystemSchema.safeParse(designSystem);
    expect(result.success).toBe(true);
  });
});

describe('API response validation', () => {
  it('should validate color intelligence API responses', () => {
    // Test response format that would come from the color intelligence API
    const apiResponse = {
      intelligence: {
        suggestedName: 'Ocean Deep',
        reasoning: 'Deep blue that evokes trust and depth',
        emotionalImpact: 'Professional, calming, and trustworthy',
        culturalContext: 'Universally positive, associated with stability',
        accessibilityNotes: 'Excellent contrast on light backgrounds, avoid on dark',
        usageGuidance: 'Perfect for primary actions and brand elements',
      },
      harmonies: {
        complementary: { l: 0.55, c: 0.18, h: 60 },
        triadic: [
          { l: 0.55, c: 0.18, h: 0 },
          { l: 0.55, c: 0.18, h: 120 },
        ],
        analogous: [
          { l: 0.55, c: 0.18, h: 210 },
          { l: 0.55, c: 0.18, h: 270 },
        ],
        tetradic: [
          { l: 0.55, c: 0.18, h: 150 },
          { l: 0.55, c: 0.18, h: 60 },
          { l: 0.55, c: 0.18, h: 330 },
        ],
        monochromatic: [
          { l: 0.75, c: 0.12, h: 240 },
          { l: 0.65, c: 0.15, h: 240 },
          { l: 0.45, c: 0.2, h: 240 },
        ],
      },
      accessibility: {
        onWhite: {
          wcagAA: true,
          wcagAAA: true,
          contrastRatio: 9.2,
          aa: [5, 6, 7, 8, 9],
          aaa: [7, 8, 9],
        },
        onBlack: {
          wcagAA: false,
          wcagAAA: false,
          contrastRatio: 1.8,
          aa: [0, 1],
          aaa: [],
        },
      },
      analysis: {
        temperature: 'cool',
        isLight: false,
        name: 'ocean-deep',
      },
    };

    const result = ColorIntelligenceResponseSchema.safeParse(apiResponse);
    expect(result.success).toBe(true);

    if (result.success) {
      expect(result.data.intelligence.suggestedName).toBe('Ocean Deep');
      expect(result.data.harmonies.triadic).toHaveLength(2);
      expect(result.data.accessibility.onWhite.wcagAAA).toBe(true);
      expect(result.data.analysis.temperature).toBe('cool');
    }
  });
});

describe('Real-world usage scenarios', () => {
  it('should handle token transformation pipeline', () => {
    // Simulate the pipeline: OKLCH -> ColorValue -> Token -> CSS

    // 1. Start with OKLCH color (from color-utils)
    const baseColor: OKLCH = { l: 0.55, c: 0.18, h: 240 };
    expect(OKLCHSchema.safeParse(baseColor).success).toBe(true);

    // 2. Create ColorValue with scale (generated by color-utils)
    const colorValue: ColorValue = {
      name: 'brand-blue',
      scale: [
        { l: 0.95, c: 0.02, h: 240 },
        { l: 0.85, c: 0.08, h: 240 },
        { l: 0.75, c: 0.12, h: 240 },
        { l: 0.65, c: 0.15, h: 240 },
        { l: 0.55, c: 0.18, h: 240 }, // Base color at index 4
        { l: 0.45, c: 0.2, h: 240 },
        { l: 0.35, c: 0.18, h: 240 },
        { l: 0.25, c: 0.15, h: 240 },
        { l: 0.15, c: 0.12, h: 240 },
        { l: 0.05, c: 0.05, h: 240 },
      ],
      value: '400', // Points to index 4
    };
    expect(ColorValueSchema.safeParse(colorValue).success).toBe(true);

    // 3. Create Token with ColorValue (used by design-tokens)
    const token: Token = {
      name: 'primary',
      value: colorValue,
      category: 'color',
      namespace: 'semantic',
      semanticMeaning: 'Primary brand color',
      trustLevel: 'high',
      cognitiveLoad: 3,
    };
    expect(TokenSchema.safeParse(token).success).toBe(true);

    // All stages should validate successfully
    expect(token.name).toBe('primary');
    expect(typeof token.value).toBe('object');
    if (typeof token.value === 'object') {
      expect(token.value.name).toBe('brand-blue');
      expect(token.value.scale).toHaveLength(10);
    }
  });

  it('should handle comprehensive accessibility metadata', () => {
    // Test the complete accessibility metadata structure that would be shared
    const accessibilityData = {
      wcagAA: {
        normal: [
          [0, 5],
          [0, 6],
          [1, 7],
          [2, 8],
        ],
        large: [
          [0, 4],
          [0, 5],
          [1, 6],
          [2, 7],
        ],
      },
      wcagAAA: {
        normal: [
          [0, 7],
          [0, 8],
          [1, 8],
        ],
        large: [
          [0, 6],
          [0, 7],
          [1, 7],
        ],
      },
      onWhite: {
        wcagAA: true,
        wcagAAA: true,
        contrastRatio: 8.9,
        aa: [5, 6, 7, 8, 9],
        aaa: [7, 8, 9],
      },
      onBlack: {
        wcagAA: false,
        wcagAAA: false,
        contrastRatio: 2.3,
        aa: [0, 1, 2],
        aaa: [0, 1],
      },
    };

    // Should validate against the accessibility schema from shared types
    expect(typeof accessibilityData.wcagAA).toBe('object');
    expect(Array.isArray(accessibilityData.wcagAA.normal)).toBe(true);
    expect(typeof accessibilityData.onWhite.contrastRatio).toBe('number');
    expect(accessibilityData.onWhite.contrastRatio).toBeGreaterThan(4.5); // Meets AA
  });
});
