import { z } from 'zod';
/**
 * AI Intelligence Types
 * These types define the structure for AI-readable design intelligence
 */
export declare const OKLCHSchema: z.ZodObject<{
    l: z.ZodNumber;
    c: z.ZodNumber;
    h: z.ZodNumber;
    alpha: z.ZodOptional<z.ZodNumber>;
}, z.core.$strip>;
export type OKLCH = z.infer<typeof OKLCHSchema>;
export declare const ColorVisionTypeSchema: z.ZodEnum<{
    normal: "normal";
    deuteranopia: "deuteranopia";
    protanopia: "protanopia";
    tritanopia: "tritanopia";
}>;
export type ColorVisionType = z.infer<typeof ColorVisionTypeSchema>;
export declare const ContrastLevelSchema: z.ZodEnum<{
    AA: "AA";
    AAA: "AAA";
}>;
export type ContrastLevel = z.infer<typeof ContrastLevelSchema>;
export declare const ComponentIntelligenceSchema: z.ZodObject<{
    cognitiveLoad: z.ZodNumber;
    attentionHierarchy: z.ZodString;
    safetyConstraints: z.ZodOptional<z.ZodString>;
    accessibilityRules: z.ZodString;
    usageContext: z.ZodString;
    decisionConstraints: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type ComponentIntelligence = z.infer<typeof ComponentIntelligenceSchema>;
export declare const IntelligenceSchema: z.ZodObject<{
    cognitiveLoad: z.ZodNumber;
    attentionEconomics: z.ZodString;
    accessibility: z.ZodString;
    trustBuilding: z.ZodString;
    semanticMeaning: z.ZodString;
}, z.core.$strip>;
export declare const UsagePatternsSchema: z.ZodObject<{
    dos: z.ZodArray<z.ZodString>;
    nevers: z.ZodArray<z.ZodString>;
}, z.core.$strip>;
export declare const DesignGuideSchema: z.ZodObject<{
    name: z.ZodString;
    url: z.ZodString;
}, z.core.$strip>;
export declare const ExampleSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    code: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type Intelligence = z.infer<typeof IntelligenceSchema>;
export declare const ColorIntelligenceSchema: z.ZodObject<{
    suggestedName: z.ZodString;
    reasoning: z.ZodString;
    emotionalImpact: z.ZodString;
    culturalContext: z.ZodString;
    accessibilityNotes: z.ZodString;
    usageGuidance: z.ZodString;
}, z.core.$strip>;
export type ColorIntelligence = z.infer<typeof ColorIntelligenceSchema>;
export declare const ColorHarmoniesSchema: z.ZodObject<{
    complementary: z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>;
    triadic: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    analogous: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    tetradic: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    monochromatic: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type ColorHarmonies = z.infer<typeof ColorHarmoniesSchema>;
export declare const ColorAccessibilitySchema: z.ZodObject<{
    wcagAA: z.ZodOptional<z.ZodObject<{
        normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
        large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
    }, z.core.$strip>>;
    wcagAAA: z.ZodOptional<z.ZodObject<{
        normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
        large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
    }, z.core.$strip>>;
    onWhite: z.ZodObject<{
        wcagAA: z.ZodBoolean;
        wcagAAA: z.ZodBoolean;
        contrastRatio: z.ZodNumber;
        aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
        aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
    }, z.core.$strip>;
    onBlack: z.ZodObject<{
        wcagAA: z.ZodBoolean;
        wcagAAA: z.ZodBoolean;
        contrastRatio: z.ZodNumber;
        aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
        aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export type ColorAccessibility = z.infer<typeof ColorAccessibilitySchema>;
export declare const ColorAnalysisSchema: z.ZodObject<{
    temperature: z.ZodEnum<{
        warm: "warm";
        cool: "cool";
        neutral: "neutral";
    }>;
    isLight: z.ZodBoolean;
    name: z.ZodString;
}, z.core.$strip>;
export type ColorAnalysis = z.infer<typeof ColorAnalysisSchema>;
export declare const AtmosphericWeightSchema: z.ZodObject<{
    distanceWeight: z.ZodNumber;
    temperature: z.ZodEnum<{
        warm: "warm";
        cool: "cool";
        neutral: "neutral";
    }>;
    atmosphericRole: z.ZodEnum<{
        background: "background";
        midground: "midground";
        foreground: "foreground";
    }>;
}, z.core.$strip>;
export type AtmosphericWeight = z.infer<typeof AtmosphericWeightSchema>;
export declare const PerceptualWeightSchema: z.ZodObject<{
    weight: z.ZodNumber;
    density: z.ZodEnum<{
        light: "light";
        medium: "medium";
        heavy: "heavy";
    }>;
    balancingRecommendation: z.ZodString;
}, z.core.$strip>;
export type PerceptualWeight = z.infer<typeof PerceptualWeightSchema>;
export declare const SemanticColorSuggestionsSchema: z.ZodObject<{
    danger: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    success: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    warning: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    info: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type SemanticColorSuggestions = z.infer<typeof SemanticColorSuggestionsSchema>;
export declare const ColorIntelligenceResponseSchema: z.ZodObject<{
    intelligence: z.ZodObject<{
        suggestedName: z.ZodString;
        reasoning: z.ZodString;
        emotionalImpact: z.ZodString;
        culturalContext: z.ZodString;
        accessibilityNotes: z.ZodString;
        usageGuidance: z.ZodString;
    }, z.core.$strip>;
    harmonies: z.ZodObject<{
        complementary: z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        triadic: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        analogous: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        tetradic: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        monochromatic: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
    }, z.core.$strip>;
    accessibility: z.ZodObject<{
        wcagAA: z.ZodOptional<z.ZodObject<{
            normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>>;
        wcagAAA: z.ZodOptional<z.ZodObject<{
            normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>>;
        onWhite: z.ZodObject<{
            wcagAA: z.ZodBoolean;
            wcagAAA: z.ZodBoolean;
            contrastRatio: z.ZodNumber;
            aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>;
        onBlack: z.ZodObject<{
            wcagAA: z.ZodBoolean;
            wcagAAA: z.ZodBoolean;
            contrastRatio: z.ZodNumber;
            aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    analysis: z.ZodObject<{
        temperature: z.ZodEnum<{
            warm: "warm";
            cool: "cool";
            neutral: "neutral";
        }>;
        isLight: z.ZodBoolean;
        name: z.ZodString;
    }, z.core.$strip>;
}, z.core.$strip>;
export type ColorIntelligenceResponse = z.infer<typeof ColorIntelligenceResponseSchema>;
export declare const SeedQueueStatsSchema: z.ZodObject<{
    strategicColors: z.ZodNumber;
    standardColors: z.ZodNumber;
    totalColors: z.ZodNumber;
    totalSent: z.ZodNumber;
}, z.core.$strip>;
export declare const SeedQueueSuccessResponseSchema: z.ZodObject<{
    success: z.ZodLiteral<true>;
    message: z.ZodString;
    stats: z.ZodObject<{
        strategicColors: z.ZodNumber;
        standardColors: z.ZodNumber;
        totalColors: z.ZodNumber;
        totalSent: z.ZodNumber;
    }, z.core.$strip>;
    timestamp: z.ZodString;
}, z.core.$strip>;
export declare const SeedQueueErrorResponseSchema: z.ZodObject<{
    success: z.ZodLiteral<false>;
    error: z.ZodString;
    timestamp: z.ZodString;
}, z.core.$strip>;
export declare const SeedQueueInfoResponseSchema: z.ZodObject<{
    endpoint: z.ZodString;
    method: z.ZodString;
    description: z.ZodString;
    expectedColors: z.ZodObject<{
        strategic: z.ZodString;
        standard: z.ZodString;
        total: z.ZodNumber;
    }, z.core.$strip>;
}, z.core.$strip>;
export type SeedQueueStats = z.infer<typeof SeedQueueStatsSchema>;
export type SeedQueueSuccessResponse = z.infer<typeof SeedQueueSuccessResponseSchema>;
export type SeedQueueErrorResponse = z.infer<typeof SeedQueueErrorResponseSchema>;
export type SeedQueueInfoResponse = z.infer<typeof SeedQueueInfoResponseSchema>;
export type SeedQueueResponse = SeedQueueSuccessResponse | SeedQueueErrorResponse;
export declare const ColorValueSchema: z.ZodObject<{
    name: z.ZodString;
    scale: z.ZodArray<z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    token: z.ZodOptional<z.ZodString>;
    value: z.ZodOptional<z.ZodString>;
    use: z.ZodOptional<z.ZodString>;
    states: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
    intelligence: z.ZodOptional<z.ZodObject<{
        suggestedName: z.ZodString;
        reasoning: z.ZodString;
        emotionalImpact: z.ZodString;
        culturalContext: z.ZodString;
        accessibilityNotes: z.ZodString;
        usageGuidance: z.ZodString;
    }, z.core.$strip>>;
    harmonies: z.ZodOptional<z.ZodObject<{
        complementary: z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>;
        triadic: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        analogous: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        tetradic: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        monochromatic: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    accessibility: z.ZodOptional<z.ZodObject<{
        wcagAA: z.ZodOptional<z.ZodObject<{
            normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>>;
        wcagAAA: z.ZodOptional<z.ZodObject<{
            normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>>;
        onWhite: z.ZodObject<{
            wcagAA: z.ZodBoolean;
            wcagAAA: z.ZodBoolean;
            contrastRatio: z.ZodNumber;
            aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>;
        onBlack: z.ZodObject<{
            wcagAA: z.ZodBoolean;
            wcagAAA: z.ZodBoolean;
            contrastRatio: z.ZodNumber;
            aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
        }, z.core.$strip>;
    }, z.core.$strip>>;
    analysis: z.ZodOptional<z.ZodObject<{
        temperature: z.ZodEnum<{
            warm: "warm";
            cool: "cool";
            neutral: "neutral";
        }>;
        isLight: z.ZodBoolean;
        name: z.ZodString;
    }, z.core.$strip>>;
    atmosphericWeight: z.ZodOptional<z.ZodObject<{
        distanceWeight: z.ZodNumber;
        temperature: z.ZodEnum<{
            warm: "warm";
            cool: "cool";
            neutral: "neutral";
        }>;
        atmosphericRole: z.ZodEnum<{
            background: "background";
            midground: "midground";
            foreground: "foreground";
        }>;
    }, z.core.$strip>>;
    perceptualWeight: z.ZodOptional<z.ZodObject<{
        weight: z.ZodNumber;
        density: z.ZodEnum<{
            light: "light";
            medium: "medium";
            heavy: "heavy";
        }>;
        balancingRecommendation: z.ZodString;
    }, z.core.$strip>>;
    semanticSuggestions: z.ZodOptional<z.ZodObject<{
        danger: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        success: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        warning: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        info: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    tokenId: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type ColorValue = z.infer<typeof ColorValueSchema>;
export declare const TokenSchema: z.ZodObject<{
    name: z.ZodString;
    value: z.ZodUnion<readonly [z.ZodString, z.ZodObject<{
        name: z.ZodString;
        scale: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        token: z.ZodOptional<z.ZodString>;
        value: z.ZodOptional<z.ZodString>;
        use: z.ZodOptional<z.ZodString>;
        states: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
        intelligence: z.ZodOptional<z.ZodObject<{
            suggestedName: z.ZodString;
            reasoning: z.ZodString;
            emotionalImpact: z.ZodString;
            culturalContext: z.ZodString;
            accessibilityNotes: z.ZodString;
            usageGuidance: z.ZodString;
        }, z.core.$strip>>;
        harmonies: z.ZodOptional<z.ZodObject<{
            complementary: z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>;
            triadic: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            analogous: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            tetradic: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            monochromatic: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        accessibility: z.ZodOptional<z.ZodObject<{
            wcagAA: z.ZodOptional<z.ZodObject<{
                normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>>;
            wcagAAA: z.ZodOptional<z.ZodObject<{
                normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>>;
            onWhite: z.ZodObject<{
                wcagAA: z.ZodBoolean;
                wcagAAA: z.ZodBoolean;
                contrastRatio: z.ZodNumber;
                aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>;
            onBlack: z.ZodObject<{
                wcagAA: z.ZodBoolean;
                wcagAAA: z.ZodBoolean;
                contrastRatio: z.ZodNumber;
                aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>;
        }, z.core.$strip>>;
        analysis: z.ZodOptional<z.ZodObject<{
            temperature: z.ZodEnum<{
                warm: "warm";
                cool: "cool";
                neutral: "neutral";
            }>;
            isLight: z.ZodBoolean;
            name: z.ZodString;
        }, z.core.$strip>>;
        atmosphericWeight: z.ZodOptional<z.ZodObject<{
            distanceWeight: z.ZodNumber;
            temperature: z.ZodEnum<{
                warm: "warm";
                cool: "cool";
                neutral: "neutral";
            }>;
            atmosphericRole: z.ZodEnum<{
                background: "background";
                midground: "midground";
                foreground: "foreground";
            }>;
        }, z.core.$strip>>;
        perceptualWeight: z.ZodOptional<z.ZodObject<{
            weight: z.ZodNumber;
            density: z.ZodEnum<{
                light: "light";
                medium: "medium";
                heavy: "heavy";
            }>;
            balancingRecommendation: z.ZodString;
        }, z.core.$strip>>;
        semanticSuggestions: z.ZodOptional<z.ZodObject<{
            danger: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            success: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            warning: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            info: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        tokenId: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>]>;
    category: z.ZodString;
    namespace: z.ZodString;
    lineHeight: z.ZodOptional<z.ZodString>;
    semanticMeaning: z.ZodOptional<z.ZodString>;
    usageContext: z.ZodOptional<z.ZodArray<z.ZodString>>;
    trustLevel: z.ZodOptional<z.ZodEnum<{
        medium: "medium";
        low: "low";
        high: "high";
        critical: "critical";
    }>>;
    cognitiveLoad: z.ZodOptional<z.ZodNumber>;
    accessibilityLevel: z.ZodOptional<z.ZodEnum<{
        AA: "AA";
        AAA: "AAA";
    }>>;
    consequence: z.ZodOptional<z.ZodEnum<{
        reversible: "reversible";
        significant: "significant";
        permanent: "permanent";
        destructive: "destructive";
    }>>;
    generatedFrom: z.ZodOptional<z.ZodString>;
    mathRelationship: z.ZodOptional<z.ZodString>;
    scalePosition: z.ZodOptional<z.ZodNumber>;
    containerQueryAware: z.ZodOptional<z.ZodBoolean>;
    pointerTypeAware: z.ZodOptional<z.ZodBoolean>;
    reducedMotionAware: z.ZodOptional<z.ZodBoolean>;
    viewportAware: z.ZodOptional<z.ZodBoolean>;
    applicableComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
    requiredForComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
    interactionType: z.ZodOptional<z.ZodEnum<{
        hover: "hover";
        focus: "focus";
        active: "active";
        disabled: "disabled";
        loading: "loading";
    }>>;
    animationSafe: z.ZodOptional<z.ZodBoolean>;
    highContrastMode: z.ZodOptional<z.ZodString>;
    generateUtilityClass: z.ZodOptional<z.ZodBoolean>;
    tailwindOverride: z.ZodOptional<z.ZodBoolean>;
    customPropertyOnly: z.ZodOptional<z.ZodBoolean>;
    contrastRatio: z.ZodOptional<z.ZodNumber>;
    touchTargetSize: z.ZodOptional<z.ZodNumber>;
    motionDuration: z.ZodOptional<z.ZodNumber>;
    pairedWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
    conflictsWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
    description: z.ZodOptional<z.ZodString>;
    deprecated: z.ZodOptional<z.ZodBoolean>;
    version: z.ZodOptional<z.ZodString>;
    lastModified: z.ZodOptional<z.ZodString>;
    generatedAt: z.ZodOptional<z.ZodString>;
    requiresConfirmation: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export type Token = z.infer<typeof TokenSchema>;
export declare const SemanticTokenSchema: z.ZodObject<{
    name: z.ZodString;
    value: z.ZodUnion<readonly [z.ZodString, z.ZodObject<{
        name: z.ZodString;
        scale: z.ZodArray<z.ZodObject<{
            l: z.ZodNumber;
            c: z.ZodNumber;
            h: z.ZodNumber;
            alpha: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        token: z.ZodOptional<z.ZodString>;
        value: z.ZodOptional<z.ZodString>;
        use: z.ZodOptional<z.ZodString>;
        states: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
        intelligence: z.ZodOptional<z.ZodObject<{
            suggestedName: z.ZodString;
            reasoning: z.ZodString;
            emotionalImpact: z.ZodString;
            culturalContext: z.ZodString;
            accessibilityNotes: z.ZodString;
            usageGuidance: z.ZodString;
        }, z.core.$strip>>;
        harmonies: z.ZodOptional<z.ZodObject<{
            complementary: z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>;
            triadic: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            analogous: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            tetradic: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            monochromatic: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        accessibility: z.ZodOptional<z.ZodObject<{
            wcagAA: z.ZodOptional<z.ZodObject<{
                normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>>;
            wcagAAA: z.ZodOptional<z.ZodObject<{
                normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>>;
            onWhite: z.ZodObject<{
                wcagAA: z.ZodBoolean;
                wcagAAA: z.ZodBoolean;
                contrastRatio: z.ZodNumber;
                aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>;
            onBlack: z.ZodObject<{
                wcagAA: z.ZodBoolean;
                wcagAAA: z.ZodBoolean;
                contrastRatio: z.ZodNumber;
                aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
            }, z.core.$strip>;
        }, z.core.$strip>>;
        analysis: z.ZodOptional<z.ZodObject<{
            temperature: z.ZodEnum<{
                warm: "warm";
                cool: "cool";
                neutral: "neutral";
            }>;
            isLight: z.ZodBoolean;
            name: z.ZodString;
        }, z.core.$strip>>;
        atmosphericWeight: z.ZodOptional<z.ZodObject<{
            distanceWeight: z.ZodNumber;
            temperature: z.ZodEnum<{
                warm: "warm";
                cool: "cool";
                neutral: "neutral";
            }>;
            atmosphericRole: z.ZodEnum<{
                background: "background";
                midground: "midground";
                foreground: "foreground";
            }>;
        }, z.core.$strip>>;
        perceptualWeight: z.ZodOptional<z.ZodObject<{
            weight: z.ZodNumber;
            density: z.ZodEnum<{
                light: "light";
                medium: "medium";
                heavy: "heavy";
            }>;
            balancingRecommendation: z.ZodString;
        }, z.core.$strip>>;
        semanticSuggestions: z.ZodOptional<z.ZodObject<{
            danger: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            success: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            warning: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            info: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        tokenId: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>]>;
    category: z.ZodString;
    namespace: z.ZodString;
    lineHeight: z.ZodOptional<z.ZodString>;
    semanticMeaning: z.ZodOptional<z.ZodString>;
    usageContext: z.ZodOptional<z.ZodArray<z.ZodString>>;
    trustLevel: z.ZodOptional<z.ZodEnum<{
        medium: "medium";
        low: "low";
        high: "high";
        critical: "critical";
    }>>;
    cognitiveLoad: z.ZodOptional<z.ZodNumber>;
    accessibilityLevel: z.ZodOptional<z.ZodEnum<{
        AA: "AA";
        AAA: "AAA";
    }>>;
    consequence: z.ZodOptional<z.ZodEnum<{
        reversible: "reversible";
        significant: "significant";
        permanent: "permanent";
        destructive: "destructive";
    }>>;
    generatedFrom: z.ZodOptional<z.ZodString>;
    mathRelationship: z.ZodOptional<z.ZodString>;
    scalePosition: z.ZodOptional<z.ZodNumber>;
    containerQueryAware: z.ZodOptional<z.ZodBoolean>;
    pointerTypeAware: z.ZodOptional<z.ZodBoolean>;
    reducedMotionAware: z.ZodOptional<z.ZodBoolean>;
    viewportAware: z.ZodOptional<z.ZodBoolean>;
    applicableComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
    requiredForComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
    interactionType: z.ZodOptional<z.ZodEnum<{
        hover: "hover";
        focus: "focus";
        active: "active";
        disabled: "disabled";
        loading: "loading";
    }>>;
    animationSafe: z.ZodOptional<z.ZodBoolean>;
    highContrastMode: z.ZodOptional<z.ZodString>;
    generateUtilityClass: z.ZodOptional<z.ZodBoolean>;
    tailwindOverride: z.ZodOptional<z.ZodBoolean>;
    customPropertyOnly: z.ZodOptional<z.ZodBoolean>;
    contrastRatio: z.ZodOptional<z.ZodNumber>;
    touchTargetSize: z.ZodOptional<z.ZodNumber>;
    motionDuration: z.ZodOptional<z.ZodNumber>;
    pairedWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
    conflictsWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
    description: z.ZodOptional<z.ZodString>;
    deprecated: z.ZodOptional<z.ZodBoolean>;
    version: z.ZodOptional<z.ZodString>;
    lastModified: z.ZodOptional<z.ZodString>;
    generatedAt: z.ZodOptional<z.ZodString>;
    requiresConfirmation: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export type SemanticToken = Token;
export declare const TokenSetSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    tokens: z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        value: z.ZodUnion<readonly [z.ZodString, z.ZodObject<{
            name: z.ZodString;
            scale: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            token: z.ZodOptional<z.ZodString>;
            value: z.ZodOptional<z.ZodString>;
            use: z.ZodOptional<z.ZodString>;
            states: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
            intelligence: z.ZodOptional<z.ZodObject<{
                suggestedName: z.ZodString;
                reasoning: z.ZodString;
                emotionalImpact: z.ZodString;
                culturalContext: z.ZodString;
                accessibilityNotes: z.ZodString;
                usageGuidance: z.ZodString;
            }, z.core.$strip>>;
            harmonies: z.ZodOptional<z.ZodObject<{
                complementary: z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>;
                triadic: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                analogous: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                tetradic: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                monochromatic: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            accessibility: z.ZodOptional<z.ZodObject<{
                wcagAA: z.ZodOptional<z.ZodObject<{
                    normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                    large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>>;
                wcagAAA: z.ZodOptional<z.ZodObject<{
                    normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                    large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>>;
                onWhite: z.ZodObject<{
                    wcagAA: z.ZodBoolean;
                    wcagAAA: z.ZodBoolean;
                    contrastRatio: z.ZodNumber;
                    aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                    aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>;
                onBlack: z.ZodObject<{
                    wcagAA: z.ZodBoolean;
                    wcagAAA: z.ZodBoolean;
                    contrastRatio: z.ZodNumber;
                    aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                    aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>;
            }, z.core.$strip>>;
            analysis: z.ZodOptional<z.ZodObject<{
                temperature: z.ZodEnum<{
                    warm: "warm";
                    cool: "cool";
                    neutral: "neutral";
                }>;
                isLight: z.ZodBoolean;
                name: z.ZodString;
            }, z.core.$strip>>;
            atmosphericWeight: z.ZodOptional<z.ZodObject<{
                distanceWeight: z.ZodNumber;
                temperature: z.ZodEnum<{
                    warm: "warm";
                    cool: "cool";
                    neutral: "neutral";
                }>;
                atmosphericRole: z.ZodEnum<{
                    background: "background";
                    midground: "midground";
                    foreground: "foreground";
                }>;
            }, z.core.$strip>>;
            perceptualWeight: z.ZodOptional<z.ZodObject<{
                weight: z.ZodNumber;
                density: z.ZodEnum<{
                    light: "light";
                    medium: "medium";
                    heavy: "heavy";
                }>;
                balancingRecommendation: z.ZodString;
            }, z.core.$strip>>;
            semanticSuggestions: z.ZodOptional<z.ZodObject<{
                danger: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                success: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                warning: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                info: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            tokenId: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>]>;
        category: z.ZodString;
        namespace: z.ZodString;
        lineHeight: z.ZodOptional<z.ZodString>;
        semanticMeaning: z.ZodOptional<z.ZodString>;
        usageContext: z.ZodOptional<z.ZodArray<z.ZodString>>;
        trustLevel: z.ZodOptional<z.ZodEnum<{
            medium: "medium";
            low: "low";
            high: "high";
            critical: "critical";
        }>>;
        cognitiveLoad: z.ZodOptional<z.ZodNumber>;
        accessibilityLevel: z.ZodOptional<z.ZodEnum<{
            AA: "AA";
            AAA: "AAA";
        }>>;
        consequence: z.ZodOptional<z.ZodEnum<{
            reversible: "reversible";
            significant: "significant";
            permanent: "permanent";
            destructive: "destructive";
        }>>;
        generatedFrom: z.ZodOptional<z.ZodString>;
        mathRelationship: z.ZodOptional<z.ZodString>;
        scalePosition: z.ZodOptional<z.ZodNumber>;
        containerQueryAware: z.ZodOptional<z.ZodBoolean>;
        pointerTypeAware: z.ZodOptional<z.ZodBoolean>;
        reducedMotionAware: z.ZodOptional<z.ZodBoolean>;
        viewportAware: z.ZodOptional<z.ZodBoolean>;
        applicableComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
        requiredForComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
        interactionType: z.ZodOptional<z.ZodEnum<{
            hover: "hover";
            focus: "focus";
            active: "active";
            disabled: "disabled";
            loading: "loading";
        }>>;
        animationSafe: z.ZodOptional<z.ZodBoolean>;
        highContrastMode: z.ZodOptional<z.ZodString>;
        generateUtilityClass: z.ZodOptional<z.ZodBoolean>;
        tailwindOverride: z.ZodOptional<z.ZodBoolean>;
        customPropertyOnly: z.ZodOptional<z.ZodBoolean>;
        contrastRatio: z.ZodOptional<z.ZodNumber>;
        touchTargetSize: z.ZodOptional<z.ZodNumber>;
        motionDuration: z.ZodOptional<z.ZodNumber>;
        pairedWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
        conflictsWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
        description: z.ZodOptional<z.ZodString>;
        deprecated: z.ZodOptional<z.ZodBoolean>;
        version: z.ZodOptional<z.ZodString>;
        lastModified: z.ZodOptional<z.ZodString>;
        generatedAt: z.ZodOptional<z.ZodString>;
        requiresConfirmation: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type TokenSet = z.infer<typeof TokenSetSchema>;
export declare const DesignSystemSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    primaryColor: z.ZodObject<{
        l: z.ZodNumber;
        c: z.ZodNumber;
        h: z.ZodNumber;
        alpha: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>;
    tokens: z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        value: z.ZodUnion<readonly [z.ZodString, z.ZodObject<{
            name: z.ZodString;
            scale: z.ZodArray<z.ZodObject<{
                l: z.ZodNumber;
                c: z.ZodNumber;
                h: z.ZodNumber;
                alpha: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            token: z.ZodOptional<z.ZodString>;
            value: z.ZodOptional<z.ZodString>;
            use: z.ZodOptional<z.ZodString>;
            states: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
            intelligence: z.ZodOptional<z.ZodObject<{
                suggestedName: z.ZodString;
                reasoning: z.ZodString;
                emotionalImpact: z.ZodString;
                culturalContext: z.ZodString;
                accessibilityNotes: z.ZodString;
                usageGuidance: z.ZodString;
            }, z.core.$strip>>;
            harmonies: z.ZodOptional<z.ZodObject<{
                complementary: z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>;
                triadic: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                analogous: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                tetradic: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                monochromatic: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            accessibility: z.ZodOptional<z.ZodObject<{
                wcagAA: z.ZodOptional<z.ZodObject<{
                    normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                    large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>>;
                wcagAAA: z.ZodOptional<z.ZodObject<{
                    normal: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                    large: z.ZodArray<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>>;
                onWhite: z.ZodObject<{
                    wcagAA: z.ZodBoolean;
                    wcagAAA: z.ZodBoolean;
                    contrastRatio: z.ZodNumber;
                    aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                    aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>;
                onBlack: z.ZodObject<{
                    wcagAA: z.ZodBoolean;
                    wcagAAA: z.ZodBoolean;
                    contrastRatio: z.ZodNumber;
                    aa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                    aaa: z.ZodOptional<z.ZodArray<z.ZodNumber>>;
                }, z.core.$strip>;
            }, z.core.$strip>>;
            analysis: z.ZodOptional<z.ZodObject<{
                temperature: z.ZodEnum<{
                    warm: "warm";
                    cool: "cool";
                    neutral: "neutral";
                }>;
                isLight: z.ZodBoolean;
                name: z.ZodString;
            }, z.core.$strip>>;
            atmosphericWeight: z.ZodOptional<z.ZodObject<{
                distanceWeight: z.ZodNumber;
                temperature: z.ZodEnum<{
                    warm: "warm";
                    cool: "cool";
                    neutral: "neutral";
                }>;
                atmosphericRole: z.ZodEnum<{
                    background: "background";
                    midground: "midground";
                    foreground: "foreground";
                }>;
            }, z.core.$strip>>;
            perceptualWeight: z.ZodOptional<z.ZodObject<{
                weight: z.ZodNumber;
                density: z.ZodEnum<{
                    light: "light";
                    medium: "medium";
                    heavy: "heavy";
                }>;
                balancingRecommendation: z.ZodString;
            }, z.core.$strip>>;
            semanticSuggestions: z.ZodOptional<z.ZodObject<{
                danger: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                success: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                warning: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                info: z.ZodArray<z.ZodObject<{
                    l: z.ZodNumber;
                    c: z.ZodNumber;
                    h: z.ZodNumber;
                    alpha: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            tokenId: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>]>;
        category: z.ZodString;
        namespace: z.ZodString;
        lineHeight: z.ZodOptional<z.ZodString>;
        semanticMeaning: z.ZodOptional<z.ZodString>;
        usageContext: z.ZodOptional<z.ZodArray<z.ZodString>>;
        trustLevel: z.ZodOptional<z.ZodEnum<{
            medium: "medium";
            low: "low";
            high: "high";
            critical: "critical";
        }>>;
        cognitiveLoad: z.ZodOptional<z.ZodNumber>;
        accessibilityLevel: z.ZodOptional<z.ZodEnum<{
            AA: "AA";
            AAA: "AAA";
        }>>;
        consequence: z.ZodOptional<z.ZodEnum<{
            reversible: "reversible";
            significant: "significant";
            permanent: "permanent";
            destructive: "destructive";
        }>>;
        generatedFrom: z.ZodOptional<z.ZodString>;
        mathRelationship: z.ZodOptional<z.ZodString>;
        scalePosition: z.ZodOptional<z.ZodNumber>;
        containerQueryAware: z.ZodOptional<z.ZodBoolean>;
        pointerTypeAware: z.ZodOptional<z.ZodBoolean>;
        reducedMotionAware: z.ZodOptional<z.ZodBoolean>;
        viewportAware: z.ZodOptional<z.ZodBoolean>;
        applicableComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
        requiredForComponents: z.ZodOptional<z.ZodArray<z.ZodString>>;
        interactionType: z.ZodOptional<z.ZodEnum<{
            hover: "hover";
            focus: "focus";
            active: "active";
            disabled: "disabled";
            loading: "loading";
        }>>;
        animationSafe: z.ZodOptional<z.ZodBoolean>;
        highContrastMode: z.ZodOptional<z.ZodString>;
        generateUtilityClass: z.ZodOptional<z.ZodBoolean>;
        tailwindOverride: z.ZodOptional<z.ZodBoolean>;
        customPropertyOnly: z.ZodOptional<z.ZodBoolean>;
        contrastRatio: z.ZodOptional<z.ZodNumber>;
        touchTargetSize: z.ZodOptional<z.ZodNumber>;
        motionDuration: z.ZodOptional<z.ZodNumber>;
        pairedWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
        conflictsWith: z.ZodOptional<z.ZodArray<z.ZodString>>;
        description: z.ZodOptional<z.ZodString>;
        deprecated: z.ZodOptional<z.ZodBoolean>;
        version: z.ZodOptional<z.ZodString>;
        lastModified: z.ZodOptional<z.ZodString>;
        generatedAt: z.ZodOptional<z.ZodString>;
        requiresConfirmation: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strip>>;
    typography: z.ZodObject<{
        heading: z.ZodString;
        body: z.ZodString;
        mono: z.ZodString;
        scale: z.ZodRecord<z.ZodString, z.ZodNumber>;
    }, z.core.$strip>;
    intelligence: z.ZodObject<{
        colorVisionTested: z.ZodArray<z.ZodEnum<{
            normal: "normal";
            deuteranopia: "deuteranopia";
            protanopia: "protanopia";
            tritanopia: "tritanopia";
        }>>;
        contrastLevel: z.ZodEnum<{
            AA: "AA";
            AAA: "AAA";
        }>;
        components: z.ZodRecord<z.ZodString, z.ZodObject<{
            cognitiveLoad: z.ZodNumber;
            attentionHierarchy: z.ZodString;
            safetyConstraints: z.ZodOptional<z.ZodString>;
            accessibilityRules: z.ZodString;
            usageContext: z.ZodString;
            decisionConstraints: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
    }, z.core.$strip>;
    metadata: z.ZodObject<{
        created: z.ZodString;
        updated: z.ZodString;
        version: z.ZodString;
    }, z.core.$strip>;
}, z.core.$strip>;
export type DesignSystem = z.infer<typeof DesignSystemSchema>;
export declare const ComponentRegistrySchema: z.ZodObject<{
    name: z.ZodString;
    type: z.ZodEnum<{
        "registry:component": "registry:component";
        "registry:lib": "registry:lib";
        "registry:style": "registry:style";
        "registry:block": "registry:block";
        "registry:page": "registry:page";
        "registry:hook": "registry:hook";
    }>;
    files: z.ZodArray<z.ZodString>;
    meta: z.ZodObject<{
        rafters: z.ZodObject<{
            intelligence: z.ZodObject<{
                cognitiveLoad: z.ZodNumber;
                attentionEconomics: z.ZodString;
                accessibility: z.ZodString;
                trustBuilding: z.ZodString;
                semanticMeaning: z.ZodString;
            }, z.core.$strip>;
        }, z.core.$strip>;
    }, z.core.$strip>;
}, z.core.$strip>;
export type ComponentRegistry = z.infer<typeof ComponentRegistrySchema>;
export declare const PublicDesignSystemSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    author: z.ZodOptional<z.ZodString>;
    primaryColor: z.ZodString;
    popularity: z.ZodDefault<z.ZodNumber>;
    downloads: z.ZodDefault<z.ZodNumber>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    preview: z.ZodOptional<z.ZodString>;
    created: z.ZodString;
}, z.core.$strip>;
export type PublicDesignSystem = z.infer<typeof PublicDesignSystemSchema>;
export declare const ComponentManifestSchema: z.ZodObject<{
    $schema: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    type: z.ZodEnum<{
        "registry:component": "registry:component";
        "registry:lib": "registry:lib";
        "registry:style": "registry:style";
        "registry:block": "registry:block";
        "registry:page": "registry:page";
        "registry:hook": "registry:hook";
    }>;
    description: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodString>;
    author: z.ZodOptional<z.ZodString>;
    dependencies: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString>>>;
    devDependencies: z.ZodOptional<z.ZodArray<z.ZodString>>;
    registryDependencies: z.ZodOptional<z.ZodArray<z.ZodString>>;
    files: z.ZodArray<z.ZodObject<{
        path: z.ZodString;
        content: z.ZodString;
        type: z.ZodString;
        target: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    tailwind: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    cssVars: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    css: z.ZodOptional<z.ZodArray<z.ZodString>>;
    envVars: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
    categories: z.ZodOptional<z.ZodArray<z.ZodString>>;
    docs: z.ZodOptional<z.ZodString>;
    meta: z.ZodOptional<z.ZodObject<{
        rafters: z.ZodOptional<z.ZodObject<{
            version: z.ZodString;
            intelligence: z.ZodObject<{
                cognitiveLoad: z.ZodNumber;
                attentionEconomics: z.ZodString;
                accessibility: z.ZodString;
                trustBuilding: z.ZodString;
                semanticMeaning: z.ZodString;
            }, z.core.$strip>;
            usagePatterns: z.ZodOptional<z.ZodObject<{
                dos: z.ZodArray<z.ZodString>;
                nevers: z.ZodArray<z.ZodString>;
            }, z.core.$strip>>;
            designGuides: z.ZodOptional<z.ZodArray<z.ZodObject<{
                name: z.ZodString;
                url: z.ZodString;
            }, z.core.$strip>>>;
            examples: z.ZodOptional<z.ZodArray<z.ZodObject<{
                title: z.ZodOptional<z.ZodString>;
                code: z.ZodString;
                description: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type ComponentManifest = z.infer<typeof ComponentManifestSchema>;
export declare const RegistryResponseSchema: z.ZodObject<{
    $schema: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    homepage: z.ZodOptional<z.ZodString>;
    components: z.ZodOptional<z.ZodArray<z.ZodObject<{
        $schema: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        type: z.ZodEnum<{
            "registry:component": "registry:component";
            "registry:lib": "registry:lib";
            "registry:style": "registry:style";
            "registry:block": "registry:block";
            "registry:page": "registry:page";
            "registry:hook": "registry:hook";
        }>;
        description: z.ZodOptional<z.ZodString>;
        title: z.ZodOptional<z.ZodString>;
        author: z.ZodOptional<z.ZodString>;
        dependencies: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString>>>;
        devDependencies: z.ZodOptional<z.ZodArray<z.ZodString>>;
        registryDependencies: z.ZodOptional<z.ZodArray<z.ZodString>>;
        files: z.ZodArray<z.ZodObject<{
            path: z.ZodString;
            content: z.ZodString;
            type: z.ZodString;
            target: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        tailwind: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        cssVars: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        css: z.ZodOptional<z.ZodArray<z.ZodString>>;
        envVars: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
        categories: z.ZodOptional<z.ZodArray<z.ZodString>>;
        docs: z.ZodOptional<z.ZodString>;
        meta: z.ZodOptional<z.ZodObject<{
            rafters: z.ZodOptional<z.ZodObject<{
                version: z.ZodString;
                intelligence: z.ZodObject<{
                    cognitiveLoad: z.ZodNumber;
                    attentionEconomics: z.ZodString;
                    accessibility: z.ZodString;
                    trustBuilding: z.ZodString;
                    semanticMeaning: z.ZodString;
                }, z.core.$strip>;
                usagePatterns: z.ZodOptional<z.ZodObject<{
                    dos: z.ZodArray<z.ZodString>;
                    nevers: z.ZodArray<z.ZodString>;
                }, z.core.$strip>>;
                designGuides: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    name: z.ZodString;
                    url: z.ZodString;
                }, z.core.$strip>>>;
                examples: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    title: z.ZodOptional<z.ZodString>;
                    code: z.ZodString;
                    description: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>>;
    items: z.ZodOptional<z.ZodArray<z.ZodObject<{
        $schema: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        type: z.ZodEnum<{
            "registry:component": "registry:component";
            "registry:lib": "registry:lib";
            "registry:style": "registry:style";
            "registry:block": "registry:block";
            "registry:page": "registry:page";
            "registry:hook": "registry:hook";
        }>;
        description: z.ZodOptional<z.ZodString>;
        title: z.ZodOptional<z.ZodString>;
        author: z.ZodOptional<z.ZodString>;
        dependencies: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString>>>;
        devDependencies: z.ZodOptional<z.ZodArray<z.ZodString>>;
        registryDependencies: z.ZodOptional<z.ZodArray<z.ZodString>>;
        files: z.ZodArray<z.ZodObject<{
            path: z.ZodString;
            content: z.ZodString;
            type: z.ZodString;
            target: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        tailwind: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        cssVars: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        css: z.ZodOptional<z.ZodArray<z.ZodString>>;
        envVars: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
        categories: z.ZodOptional<z.ZodArray<z.ZodString>>;
        docs: z.ZodOptional<z.ZodString>;
        meta: z.ZodOptional<z.ZodObject<{
            rafters: z.ZodOptional<z.ZodObject<{
                version: z.ZodString;
                intelligence: z.ZodObject<{
                    cognitiveLoad: z.ZodNumber;
                    attentionEconomics: z.ZodString;
                    accessibility: z.ZodString;
                    trustBuilding: z.ZodString;
                    semanticMeaning: z.ZodString;
                }, z.core.$strip>;
                usagePatterns: z.ZodOptional<z.ZodObject<{
                    dos: z.ZodArray<z.ZodString>;
                    nevers: z.ZodArray<z.ZodString>;
                }, z.core.$strip>>;
                designGuides: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    name: z.ZodString;
                    url: z.ZodString;
                }, z.core.$strip>>>;
                examples: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    title: z.ZodOptional<z.ZodString>;
                    code: z.ZodString;
                    description: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export type RegistryResponse = z.infer<typeof RegistryResponseSchema>;
