
export default new Map([
["src/content/foundation/color-system.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundation%2Fcolor-system.mdx&astroContentModuleFlag=true")],
["src/content/foundation/design-intelligence.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundation%2Fdesign-intelligence.mdx&astroContentModuleFlag=true")],
["src/content/foundation/getting-started.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundation%2Fgetting-started.mdx&astroContentModuleFlag=true")],
["src/content/foundation/mcp-server.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundation%2Fmcp-server.mdx&astroContentModuleFlag=true")],
["src/content/foundation/typography.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Ffoundation%2Ftypography.mdx&astroContentModuleFlag=true")],
["src/content/components/badge.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fbadge.mdx&astroContentModuleFlag=true")],
["src/content/components/breadcrumb.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fbreadcrumb.mdx&astroContentModuleFlag=true")],
["src/content/components/button.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fbutton.mdx&astroContentModuleFlag=true")],
["src/content/components/chip.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fchip.mdx&astroContentModuleFlag=true")],
["src/content/components/card.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fcard.mdx&astroContentModuleFlag=true")],
["src/content/components/dialog.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fdialog.mdx&astroContentModuleFlag=true")],
["src/content/components/grid.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fgrid.mdx&astroContentModuleFlag=true")],
["src/content/components/container.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fcontainer.mdx&astroContentModuleFlag=true")],
["src/content/components/example.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fexample.mdx&astroContentModuleFlag=true")],
["src/content/components/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/components/input.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Finput.mdx&astroContentModuleFlag=true")],
["src/content/components/label.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Flabel.mdx&astroContentModuleFlag=true")],
["src/content/components/progress.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fprogress.mdx&astroContentModuleFlag=true")],
["src/content/components/select.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fselect.mdx&astroContentModuleFlag=true")],
["src/content/components/sidebar.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fsidebar.mdx&astroContentModuleFlag=true")],
["src/content/components/tabs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Ftabs.mdx&astroContentModuleFlag=true")],
["src/content/components/toast.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Ftoast.mdx&astroContentModuleFlag=true")],
["src/content/components/slider.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Fslider.mdx&astroContentModuleFlag=true")],
["src/content/components/tooltip.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcomponents%2Ftooltip.mdx&astroContentModuleFlag=true")]]);
		