/**
 * Tests for Tailwind v4 CSS Exporter
 */

import type { Token } from '@rafters/shared';
import { describe, expect, it } from 'vitest';
import { registryToTailwind, tokensToTailwind } from '../../src/exporters/tailwind.js';
import { TokenRegistry } from '../../src/registry.js';

describe('tokensToTailwind', () => {
  it('should export semantic tokens to :root', () => {
    const tokens: Token[] = [
      { name: 'primary', value: 'oklch(0.55 0.12 240)', category: 'color', namespace: 'semantic' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain(':root {');
    expect(css).toContain('--primary: oklch(0.55 0.12 240);');
  });

  it('should export color scales to @theme inline', () => {
    const tokens: Token[] = [
      { name: 'neutral-500', value: 'oklch(0.55 0 0)', category: 'color', namespace: 'color' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('@theme inline {');
    expect(css).toContain('--color-neutral-500: oklch(0.55 0 0);');
  });

  it('should bridge semantic tokens with color prefix', () => {
    const tokens: Token[] = [
      { name: 'primary', value: 'oklch(0.55 0.12 240)', category: 'color', namespace: 'semantic' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--primary: oklch(0.55 0.12 240);');
    expect(css).toContain('--color-primary: var(--primary);');
  });

  it('should export spacing tokens', () => {
    const tokens: Token[] = [
      { name: 'spacing-4', value: '1rem', category: 'spacing', namespace: 'spacing' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--spacing-4: 1rem;');
  });

  it('should export typography tokens with line-height companions', () => {
    const tokens: Token[] = [
      {
        name: 'text-base',
        value: '1rem',
        category: 'typography',
        namespace: 'typography',
        lineHeight: '1.5',
      },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--text-base: 1rem;');
    expect(css).toContain('--text-base--line-height: 1.5;');
  });

  it('should handle dark mode tokens', () => {
    interface TokenWithVariant extends Token {
      themeVariant?: 'light' | 'dark';
    }

    const tokens: TokenWithVariant[] = [
      { name: 'background', value: 'oklch(0.985 0 0)', category: 'color', namespace: 'semantic' },
      {
        name: 'background',
        value: 'oklch(0.141 0 0)',
        category: 'color',
        namespace: 'semantic',
        themeVariant: 'dark',
      },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain(':root {');
    expect(css).toContain('--background: oklch(0.985 0 0);');
    expect(css).toContain('.dark {');
    expect(css).toContain('--background: oklch(0.141 0 0);');
  });

  it('should throw if registry is empty', () => {
    expect(() => tokensToTailwind([])).toThrow('Registry is empty');
  });

  it('should include header comment', () => {
    const tokens: Token[] = [
      { name: 'test', value: 'value', category: 'test', namespace: 'other' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('/* Generated by Rafters - DO NOT EDIT */');
  });

  it('should include @import tailwindcss by default', () => {
    const tokens: Token[] = [
      { name: 'test', value: 'value', category: 'test', namespace: 'other' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('@import "tailwindcss";');
  });

  it('should omit @import when includeImport=false', () => {
    const tokens: Token[] = [
      { name: 'test', value: 'value', category: 'test', namespace: 'other' },
    ];

    const css = tokensToTailwind(tokens, { includeImport: false });

    expect(css).not.toContain('@import "tailwindcss";');
  });

  it('should use custom dark mode selector', () => {
    interface TokenWithVariant extends Token {
      themeVariant?: 'light' | 'dark';
    }

    const tokens: TokenWithVariant[] = [
      {
        name: 'background',
        value: 'oklch(0.141 0 0)',
        category: 'color',
        namespace: 'semantic',
        themeVariant: 'dark',
      },
    ];

    const css = tokensToTailwind(tokens, { darkModeSelector: '[data-theme="dark"]' });

    expect(css).toContain('[data-theme="dark"] {');
  });

  it('should include comments when includeComments=true', () => {
    const tokens: Token[] = [
      {
        name: 'primary',
        value: 'blue',
        category: 'color',
        namespace: 'semantic',
        description: 'Primary action color',
      },
    ];

    const css = tokensToTailwind(tokens, { includeComments: true });

    expect(css).toContain('/* Primary action color */');
  });

  it('should export radius tokens', () => {
    const tokens: Token[] = [
      { name: 'radius-sm', value: '0.25rem', category: 'radius', namespace: 'radius' },
      { name: 'radius-md', value: '0.375rem', category: 'radius', namespace: 'radius' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--radius-sm: 0.25rem;');
    expect(css).toContain('--radius-md: 0.375rem;');
  });

  it('should export shadow tokens', () => {
    const tokens: Token[] = [
      {
        name: 'shadow-sm',
        value: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        category: 'shadow',
        namespace: 'shadow',
      },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);');
  });

  it('should export depth tokens', () => {
    const tokens: Token[] = [
      { name: 'depth-dropdown', value: '10', category: 'depth', namespace: 'depth' },
      { name: 'depth-modal', value: '50', category: 'depth', namespace: 'depth' },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--depth-dropdown: 10;');
    expect(css).toContain('--depth-modal: 50;');
  });

  it('should export motion tokens', () => {
    const tokens: Token[] = [
      { name: 'duration-fast', value: '150ms', category: 'motion', namespace: 'motion' },
      {
        name: 'easing-ease-out',
        value: 'cubic-bezier(0, 0, 0.2, 1)',
        category: 'motion',
        namespace: 'motion',
      },
    ];

    const css = tokensToTailwind(tokens);

    expect(css).toContain('--duration-fast: 150ms;');
    expect(css).toContain('--easing-ease-out: cubic-bezier(0, 0, 0.2, 1);');
  });
});

describe('registryToTailwind', () => {
  it('should convert registry to Tailwind CSS', () => {
    const registry = new TokenRegistry([
      { name: 'primary', value: 'oklch(0.55 0.12 240)', category: 'color', namespace: 'semantic' },
    ]);

    const css = registryToTailwind(registry);

    expect(css).toContain(':root {');
    expect(css).toContain('--primary: oklch(0.55 0.12 240);');
  });

  it('should accept options', () => {
    const registry = new TokenRegistry([
      {
        name: 'primary',
        value: 'blue',
        category: 'color',
        namespace: 'semantic',
        description: 'Primary color',
      },
    ]);

    const css = registryToTailwind(registry, { includeComments: true });

    expect(css).toContain('/* Primary color */');
  });
});
